lib/projectFitAcademy_web/router.ex
defmodule ProjectFitAcademyWeb.Router do
  use ProjectFitAcademyWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {ProjectFitAcademyWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ProjectFitAcademyWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/users", UserController
    resources "/uploads", UploadController, only: [:create, :show]
  end


  # Other scopes may use custom stacks.
  # scope "/api", ProjectFitAcademyWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: ProjectFitAcademyWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/projectFitAcademy/users.ex
defmodule ProjectFitAcademy.Users do
  @moduledoc """
  The Users context.
  """

  import Ecto.Query, warn: false
  alias ProjectFitAcademy.Repo

  alias ProjectFitAcademy.Users.User
  alias ProjectFitAcademy.Documents.Upload

  @doc """
  Returns the list of users.

  ## Examples

      iex> list_users()
      [%User{}, ...]

  """
  def list_users do
    Repo.all(User)
  end

  @doc """
  Gets a single user.

  Raises `Ecto.NoResultsError` if the User does not exist.

  ## Examples

      iex> get_user!(123)
      %User{}

      iex> get_user!(456)
      ** (Ecto.NoResultsError)

  """
  def get_user!(id), do: Repo.get!(User, id)

  @doc """
  Creates a user.

  ## Examples

      iex> create_user(%{field: value})
      {:ok, %User{}}

      iex> create_user(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_user(attrs \\ %{}) do
    %User{}
    |> User.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a user.

  ## Examples

      iex> update_user(user, %{field: new_value})
      {:ok, %User{}}

      iex> update_user(user, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_user(%User{} = user, attrs) do
    user
    |> User.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a user.

  ## Examples

      iex> delete_user(user)
      {:ok, %User{}}

      iex> delete_user(user)
      {:error, %Ecto.Changeset{}}

  """
  def delete_user(%User{} = user) do
    Repo.delete(user)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking user changes.

  ## Examples

      iex> change_user(user)
      %Ecto.Changeset{data: %User{}}

  """
  def change_user(%User{} = user, attrs \\ %{}) do
    User.changeset(user, attrs)
  end
end

lib/projectFitAcademy/users/user.ex
defmodule ProjectFitAcademy.Users.User do
  use Ecto.Schema
  import Ecto.Changeset

  schema "users" do
    field :email, :string
    field :name, :string
    field :password, :string
    field :police, Ecto.Enum, values: [:Admin, :Supervisor, :Teacher, :Studants]
    field :gender, Ecto.Enum, values: [:Feminine, :Male]
    timestamps()
  end

  @doc false
  def changeset(user, attrs) do
    user
    |> cast(attrs, [:name, :email, :password, :police, :gender])
    |> validate_required([:name, :email, :password, :police])
    |> unique_constraint(:email)
  end

end

lib/projectFitAcademy_web/controllers/user_controller.ex
defmodule ProjectFitAcademyWeb.UserController do
  use ProjectFitAcademyWeb, :controller

  alias ProjectFitAcademy.Users
  alias ProjectFitAcademy.Users.User
  alias ProjectFitAcademy.Documents.Upload


  def index(conn, _params) do
    users = Users.list_users()
    render(conn, "index.html", users: users)
  end

  def new(conn, _params) do
    changeset = Users.change_user(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  
  
  def create(conn, %{"user" => user_params}) do
    case Users.create_user(user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User created successfully.")
        |> redirect(to: Routes.user_path(conn, :show, user))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    user = Users.get_user!(id)
    render(conn, "show.html", user: user)
  end

  def edit(conn, %{"id" => id}) do
    user = Users.get_user!(id)
    changeset = Users.change_user(user)
    render(conn, "edit.html", user: user, changeset: changeset)
  end

  def update(conn, %{"id" => id, "user" => user_params}) do
    user = Users.get_user!(id)

    case Users.update_user(user, user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User updated successfully.")
        |> redirect(to: Routes.user_path(conn, :show, user))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", user: user, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    user = Users.get_user!(id)
    {:ok, _user} = Users.delete_user(user)

    conn
    |> put_flash(:info, "User deleted successfully.")
    |> redirect(to: Routes.user_path(conn, :index))
  end
end

lib/projectFitAcademy_web/views/user_view.ex
defmodule ProjectFitAcademyWeb.UserView do
  use ProjectFitAcademyWeb, :view
end

lib/projectFitAcademy_web/templates/user/edit.html.heex
<h1>Edit User</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.user_path(@conn, :update, @user)) %>

<span><%= link "Back", to: Routes.user_path(@conn, :index) %></span>

<%= form_for @conn, Routes.upload_path(@conn, :create), 
[multipart: true], fn f-> %>

<%= file_input f, :upload, class: "form-control", id: "img-input" %>
<%= text_input f, :user_id, class: "form-control", value: @user.id, id: "input-none" %>
<%= submit "Upload", class: "btn btn-primary" %>

<% end %>

lib/projectFitAcademy_web/templates/user/form.html.heex
<.form let={f} for={@changeset} action={@action} multipart={true}>
  <div class="content">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header">
            <h5 class="title">Create New User</h5>
          </div>
          <div class="card-body form-group" style="margin: 0 auto">
            <%= if @changeset.action do %>
            <div class="alert alert-danger">
              <p>Oops, something went wrong! Please check the errors below.</p>
            </div>
            <% end %>

            <%= label f, :name %>
            <%= text_input f, :name, class: "form-control", id: "name" %>
            <%= error_tag f, :name %>

            <%= label f, :email %>
            <%= text_input f, :email, class: "form-control", id: "email" %>
            <%= error_tag f, :email %>

            <%= label f, :password %>
            <%= password_input f, :password, class: "form-control" %>
            <%= error_tag f, :password %>
            <div class="col-md-6 left" style="margin-bottom: 20px; padding-left:0;">
              <%= label f, :police %>
              <%= select f, :police, [:"", :Admin, :Supervisor, :Teacher, :Students], class: "form-control" %>
              <%= error_tag f, :police %>
            </div>
            <div class="col-md-6 right" style="margin-bottom: 20px; padding-right:0;">
              <%= label f, :gender %>
              <%= select f, :gender, [:"", :Feminine, :Male], class: "form-control" %>
              <%= error_tag f, :gender %>
            </div>


            <%= submit "Save", class: "btn btn-primary col-md-12"%>
            <div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</.form>

lib/projectFitAcademy_web/templates/user/index.html.heex
<div class="content">
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <h5 class="title">List User</h5>
        </div>
        <div class="card-body form-group" style="margin: 0 auto">
          <div class="table-responsive">
            <table class="table">
              <thead class="text-primary">
                <tr>
                  <th>Name</th>
                  <th>Email</th>
                  <th>Police</th>

                  <th></th>
                </tr>
              </thead>
              <tbody>
                <%= for user <- @users do %>
                <tr>
                  <td><%= user.name %></td>
                  <td><%= user.email %></td>
                  <td><%= user.police %></td>

                  <td>
                    <span class="spanedit">
                      <%= link to: Routes.user_path(@conn, :show, user) do %>
                      <label>Show User</label>
                      <i class="now-ui-icons users_single-02" alt="Show User"></i>
                      <% end %>
                    </span>
                    <span class="spanedit">
                      <%= link to: Routes.user_path(@conn, :edit, user) do %>
                      <label>Edit User</label>
                      <i class="now-ui-icons design-2_ruler-pencil" alt="Edit User"></i>
                      <% end %>
                    </span>
                    <span>
                      <%= link  to: Routes.user_path(@conn, :delete, user), method: :delete, data: [confirm: "Are you sure?"] do %>
                      <label>Delete User</label>
                      <i class="now-ui-icons ui-1_simple-remove" alt="Delete User"></i>
                      <% end %>
                    </span>
                  </td>
                </tr>
                <% end %>
              </tbody>
            </table>

            <span><%= link("Create New User", to: Routes.user_path(@conn, :new), class: "btn btn-primary") %></span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

lib/projectFitAcademy_web/templates/user/new.html.heex
<%= render "form.html", Map.put(assigns, :action, Routes.user_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.user_path(@conn, :index) %></span>

lib/projectFitAcademy_web/templates/user/show.html.heex
<div class="content">
  <div class="row">
    <div class="col-md-4">
      <div class="card card-user">
        <div class="image">
          <img src="../assets/img/bg5.jpg" alt="...">
        </div>
        <div class="card-body">
          <div class="author">
            <a href="#">
              <%= if @user.gender === :Male do %>
              <img class="avatar border-gray" id="preview" src="../assets/img/avatar-male.jpeg" alt="...">
              <% else %>
              <img class="avatar border-gray" id="preview" src="../assets/img/avatar-generico.png" alt="...">
              <% end %>
            </a>
            <p class="description">
            </p>
          </div>
          <h5 class="title"><%= @user.name %></h5>
          <ul class="description">
            <li>
              <strong>Email:</strong>
              <%= @user.email %>
            </li>

            <li>
              <strong>Police:</strong>
              <%= @user.police %>
            </li>
            <li>
              <strong>Gender:</strong>
              <%= @user.gender %>
            </li>
          </ul>

          <span><%= link "Edit", to: Routes.user_path(@conn, :edit, @user) %></span> |
          <span><%= link "Back", to: Routes.user_path(@conn, :index) %></span>
        </div>
        <hr>
      </div>
    </div>
  </div>
  <script type="text/javascript">
    function readImage() {
      if (this.files && this.files[0]) {
        var file = new FileReader();
        file.onload = function (e) {
          document.getElementById("preview").src = e.target.result;
        };
        file.readAsDataURL(this.files[0]);
      }
    }

    document.getElementById("img-input").addEventListener("change", readImage, false);
  </script>
</div>